spring:
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 2000MB
      # 设置单次请求文件的总大小
      max-request-size: 2000MB
  datasource:
    # 配置数据源
    username: root
    password: WHL531124
    url: jdbc:mysql://101.43.95.238:3306/software_crm?serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置druid数据源
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 101.43.95.238
    port: 6379
    database: 6 #Redis数据库索引（默认为0）
    password: WHL531124
    timeout: 1800000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接


server:
  port: 3964
  servlet:
    context-path: /api

releasedao:
  config:
    camel-case: true #开启 驼峰自动转蛇形式 默认true
    logger: true #开启 日志输出 ，默认false
    cache: true #是否开启缓存，默认false
    cache-expired-time: 604800 #缓存过期时间 默认七天